

name: documentation
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./web-fit

    permissions:
      contents: 'read'
      pages: 'write'
      id-token: 'write'

    steps:
      - name: Clona reposit칩rio no servidor remoto do GitHub
        uses: actions/checkout@v5
        
      - name: Configura o interpretador Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Instala bibliotecas Python
        run: |
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt
          
      - name: Constr칩i p치ginas HTML com MKDocs
        run: mkdocs build
        
      - name: Configura o deploy para o GitHub Pages
        uses: actions/configure-pages@v3

      - name: Faz upload do artefato para o GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web-fit/site/'

      - name: Publica p치ginas HTML
        id: deployment
        uses: actions/deploy-pages@v4